name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг для клонирования репозитория
      - uses: actions/checkout@v4

      # Шаг для создания файла
      - name: Create a new file
        run: |
          echo "This is a build file" > build.txt
