name: Windows CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest # Используем Windows Runner

    steps:
      # Шаг для клонирования репозитория
      - uses: actions/checkout@v4

      # Шаг для создания файла на диске D:
      - name: create a new file on D drive
        run: echo "This is a build file" > D:\build.txt
        shell: cmd